SELECT M.MEMBER_NAME, R1.REVIEW_TEXT, DATE_FORMAT(R1.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE M
JOIN REST_REVIEW R1 ON M.MEMBER_ID = R1.MEMBER_ID
JOIN (SELECT MEMBER_ID
      FROM REST_REVIEW 
      GROUP BY MEMBER_ID 
      ORDER BY COUNT(*) DESC 
      LIMIT 1) R2
      ON R2.MEMBER_ID = R1.MEMBER_ID
ORDER BY R1.REVIEW_DATE, R1.REVIEW_TEXT