SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE * ((100 - P.DISCOUNT_RATE) * 0.01) * 30 AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON P.CAR_TYPE = C.CAR_TYPE
WHERE C.CAR_TYPE IN ('SUV','세단')
    AND P.DURATION_TYPE = '30일 이상'
    AND C.CAR_ID NOT IN (
        SELECT CAR_ID 
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H 
        WHERE H.START_DATE < '2022-12-01' AND H.END_DATE > '2022-10-31'
    )
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC