SELECT EXTRACT(YEAR FROM DIFFERENTIATION_DATE) AS YEAR, (MAX_SIZE - SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM (
    SELECT 
        ID, 
        SIZE_OF_COLONY,
        DIFFERENTIATION_DATE,
        EXTRACT(YEAR FROM DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) OVER (PARTITION BY EXTRACT(YEAR FROM DIFFERENTIATION_DATE)) AS MAX_SIZE
    FROM ECOLI_DATA
) AS E
ORDER BY YEAR, YEAR_DEV;