SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D
CROSS JOIN (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') P
CROSS JOIN (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') C
WHERE P.CODE & D.SKILL_CODE > 0 OR C.CODE & D.SKILL_CODE > 0
ORDER BY ID;