SELECT 
    H.HISTORY_ID, 
    C.DAILY_FEE * (100 - IFNULL(P.DISCOUNT_RATE,0)) * 0.01 * (DATEDIFF(H.END_DATE,H.START_DATE) + 1) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN CAR_RENTAL_COMPANY_CAR C 
    ON H.CAR_ID = C.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P 
    ON C.CAR_TYPE = P.CAR_TYPE
    AND (
        (P.DURATION_TYPE = '7일 이상' AND DATEDIFF(H.END_DATE, H.START_DATE) + 1 BETWEEN 7 AND 29) 
        OR 
        (P.DURATION_TYPE = '30일 이상' AND DATEDIFF(H.END_DATE, H.START_DATE) + 1 BETWEEN 30 AND 89) 
        OR 
        (P.DURATION_TYPE = '90일 이상' AND DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90) 
    )
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC