SELECT 
    CASE 
        WHEN (D.SKILL_CODE & F.CODE) > 0 AND (D.SKILL_CODE & P.CODE) > 0 THEN 'A'
        WHEN (D.SKILL_CODE & C.CODE) > 0 THEN 'B'
        WHEN (D.SKILL_CODE & F.CODE) > 0 THEN 'C'
    END AS GRADE, 
    D.ID, 
    D.EMAIL
FROM DEVELOPERS D
CROSS JOIN (SELECT SUM(CODE) AS CODE FROM SKILLCODES WHERE CATEGORY = 'Front End') F
CROSS JOIN (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') P
CROSS JOIN (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') C
WHERE 
    ((D.SKILL_CODE & F.CODE) > 0 AND (D.SKILL_CODE & P.CODE)) > 0 
    OR (D.SKILL_CODE & C.CODE) > 0
    OR (D.SKILL_CODE & F.CODE) > 0
ORDER BY GRADE, ID;