SELECT B.CATEGORY, SUM(B2.SALES) AS TOTAL_SALES
FROM BOOK B
JOIN (
    SELECT BOOK_ID, SALES
    FROM BOOK_SALES
    WHERE SALES_DATE LIKE '2022-01-%'
) B2 ON B2.BOOK_ID = B.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY